name: Toronto Wedding Minister
favicon: null
layout_spectrum: 0.33370381710119545
typography_spectrum: 0.6085007963702083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.16632775939069688
  lightness: 0.9314532643184066
  saturation: 0.9497181081678718
  rhythmicContrast: 0.4740229439921677
purpose: []
